### ISSUE TITLE
CSharp intellisense occasionally fails with an exception

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Razor.VSCode#214]
I couldn't get a consistent repro but it happens occasionally when I try to type DateTime.Now in line 5.

![image](https://user-images.githubusercontent.com/1579269/47539229-171f2580-d884-11e8-9d8a-46e4f9c04ecb.png)

I don't get the expected CSharp intellisense and the following exception is thrown
```
Failed to synchronize document '/Users/ajbaaska/Github/temp/RazorVSCodeTest/Pages/Index.cshtml__virtual.cs': "System.ArgumentException: An item with the same key has already been added. Key: /Users/ajbaaska/Github/temp/RazorVSCodeTest/Pages/Index.cshtml__virtual.cs
  at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x000ad] in <0f9df4881040473f9da7cf6c2e2cb8c3>:0 
  at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <0f9df4881040473f9da7cf6c2e2cb8c3>:0 
  at OmniSharp.Roslyn.BufferManager.TryAddTransientDocument (System.String fileName, System.String fileContent) [0x00101] in <87f0b9e659494985a2da11f6102d4a4b>:0 
  at OmniSharp.Roslyn.BufferManager+<UpdateBufferAsync>d__7.MoveNext () [0x0028c] in <87f0b9e659494985a2da11f6102d4a4b>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <0f9df4881040473f9da7cf6c2e2cb8c3>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <0f9df4881040473f9da7cf6c2e2cb8c3>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <0f9df4881040473f9da7cf6c2e2cb8c3>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <0f9df4881040473f9da7cf6c2e2cb8c3>:0 
  at OmniSharp.Roslyn.CSharp.Services.Buffer.UpdateBufferService+<Handle>d__2.MoveNext () [0x00072] in <7e8bc09baf3d4b52839d77f569cbdb5f>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <0f9df4881040473f9da7cf6c2e2cb8c3>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <0f9df4881040473f9da7cf6c2e2cb8c3>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <0f9df4881040473f9da7cf6c2e2cb8c3>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <0f9df4881040473f9da7cf6c2e2cb8c3>:0 
  at OmniSharp.Endpoint.EndpointHandler`2+<HandleSingleRequest>d__18[TRequest,TResponse].MoveNext () [0x000e4] in <3c50833d933444f18e15117ec743f98f>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <0f9df4881040473f9da7cf6c2e2cb8c3>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <0f9df4881040473f9da7cf6c2e2cb8c3>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <0f9df4881040473f9da7cf6c2e2cb8c3>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <0f9df4881040473f9da7cf6c2e2cb8c3>:0 
  at OmniSharp.Endpoint.EndpointHandler`2+<Process>d__16[TRequest,TResponse].MoveNext () [0x0024b] in <3c50833d933444f18e15117ec743f98f>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <0f9df4881040473f9da7cf6c2e2cb8c3>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <0f9df4881040473f9da7cf6c2e2cb8c3>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <0f9df4881040473f9da7cf6c2e2cb8c3>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <0f9df4881040473f9da7cf6c2e2cb8c3>:0 
  at OmniSharp.Stdio.Host+<HandleRequest>d__13.MoveNext () [0x000e7] in <33e072d1bf1148378944302c3cd641c2>:0 "
```

VS Code version: 1.28.2 
Omnisharp version: 1.17.0-beta7
OS: MacOS Mojave
Project template: dotnet new razor
dotnet SDK version: 2.2.100-preview2-009404

**Comment by ajaybhargavb** [comment]
This is probably what was mentioned in known issues as `Leaving Razor files open for a significant period of time results in loss of Razor C# tooling on macOS`. I tested how long it takes for this exception to appear and it usually happens after 3 minutes of the document being open.

**Comment by danroth27** [comment]
I hit something similar to this on Windows:

```
Failed to synchronize document '/c:/Users/daroth/Desktop/WebApp3/WebApp4/Pages/About.cshtml__virtual.cs': "System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at OmniSharp.Roslyn.BufferManager.TryAddTransientDocument(String fileName, String fileContent)
   at OmniSharp.Roslyn.BufferManager.<UpdateBufferAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Roslyn.CSharp.Services.Buffer.UpdateBufferService.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Endpoint.EndpointHandler`2.<HandleSingleRequest>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Endpoint.EndpointHandler`2.<Process>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Stdio.Host.<HandleRequest>d__13.MoveNext()"
```

**Comment by NTaylorMullen** [comment]
https://github.com/OmniSharp/omnisharp-roslyn/commit/de5f66f7533623fbd72005ad52375fb0707a36a2
