### ISSUE TITLE
OpenSUSE Tumbleweed - Couldn't find a valid ICU package

### ISSUE THREAD

**Issue by savornicesei** [aspnet/Razor.VSCode#243]
Hi all,
I want to report a bug resolved [upstream (in .NET core)](https://github.com/dotnet/core-setup/issues/4413) caused by a change in the name of libicu lib on OpenSUSE Tumbleweed.

#### Description of the problem:
When I open Visual Studio Code (opened project has no web element or reference in it), the Razor Log shows:
```
--------------------------------------------------------------------------------
Razor.VSCode version 1.0.0-alpha2-20181112.3
--------------------------------------------------------------------------------
Razor's trace level is currently set to 'Off'
 - To log issues with the Razor experience in VSCode you can file issues at https://github.com/aspnet/Razor.VSCode
 - To change Razor's trace level set 'razor.trace' to 'Off', 'Messages' or 'Verbose' and then restart VSCode.
-----------------------------------------------------------------------------------------------------------------------------

FailFast: Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.

   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureData.GetCultureData(System.String, Boolean)
   at System.Globalization.CultureInfo.InitializeFromName(System.String, Boolean)
   at System.Globalization.CultureInfo.Init()
   at System.Globalization.CultureInfo..cctor()
   at System.StringComparer..cctor()
   at System.AppDomainSetup.SetCompatibilitySwitches(System.Collections.Generic.IEnumerable`1<System.String>)
   at System.AppDomain.PrepareDataForSetup(System.String, System.AppDomainSetup, System.Security.Policy.Evidence, System.Security.Policy.Evidence, IntPtr, System.String, System.String[], System.String[])
[Info  - 22:23:49] Connection to server got closed. Server will restart.
[Error - 22:23:49] Connection to server is erroring. Shutting down server.
FailFast: Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.

   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureData.GetCultureData(System.String, Boolean)
   at System.Globalization.CultureInfo.InitializeFromName(System.String, Boolean)
   at System.Globalization.CultureInfo.Init()
   at System.Globalization.CultureInfo..cctor()
   at System.StringComparer..cctor()
   at System.AppDomainSetup.SetCompatibilitySwitches(System.Collections.Generic.IEnumerable`1<System.String>)
   at System.AppDomain.PrepareDataForSetup(System.String, System.AppDomainSetup, System.Security.Policy.Evidence, System.Security.Policy.Evidence, IntPtr, System.String, System.String[], System.String[])
[Error - 22:23:49] Connection to server is erroring. Shutting down server.
`

The C# output shows no issue:
`Installing C# dependencies...
Platform: linux, x86_64, name=opensuse-tumbleweed, version=20181122

Downloading package 'OmniSharp for Linux (x64)' (30903 KB).................... Done!
Installing package 'OmniSharp for Linux (x64)'

Downloading package '.NET Core Debugger (linux / x64)' (59407 KB).................... Done!
Installing package '.NET Core Debugger (linux / x64)'

Downloading package 'Razor Language Server (Linux / x64)' (44979 KB).................... Done!
Installing package 'Razor Language Server (Linux / x64)'

Finished
```

And no issues reported in OmniSharp Log as well.

#### Additional information
* Visual Studio Code
Version: 1.29.1
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:07:43.495Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

```
simona@devrog:~> uname -a
Linux devrog.avornicesei.com 4.19.2-1-default #1 SMP PREEMPT Tue Nov 13 20:56:49 UTC 2018 (8adee6e) x86_64 x86_64 x86_64 GNU/Linux
simona@devrog:~> dotnet --version
2.1.500
simona@devrog:~> pwsh --version
PowerShell 6.1.1
```

Thank you.

**Comment by savornicesei** [comment]
Thank  you, @NTaylorMullen 
Looking forward for the next update....

**Comment by mkArtakMSFT** [comment]
We're closing this as we track this as part of updating .Net Core SDK change. Stay tuned for Alpha3 release.
