### ISSUE TITLE
Unhandled Exception: System.ArgumentOutOfRangeException: Length cannot be less than zero.

### ISSUE THREAD

**Issue by SmGG** [aspnet/Razor.VSCode#252]
razor server failed

>Unhandled Exception: System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at System.Uri.CreateHostStringHelper(String str, UInt16 idx, UInt16 end, Flags& flags, String& scopeId)
   at System.Uri.CreateHostString()
   at System.Uri.EnsureHostString(Boolean allowDnsOptimization)
   at System.Uri.GetComponentsHelper(UriComponents uriComponents, UriFormat uriFormat)
   at System.Uri.ToString()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at OmniSharp.Extensions.LanguageServer.Server.Matchers.TextDocumentMatcher.FindHandler(Object parameters, IEnumerable`1 descriptors)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.FindDescriptor(String method, JToken params)
   at OmniSharp.Extensions.JsonRpc.InputHandler.HandleRequest(String request)
   at OmniSharp.Extensions.JsonRpc.InputHandler.ProcessInputStream()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
[Info  - 10:05:04 AM] Connection to server got closed. Server will restart.
[Info  - 10:05:05 AM] Razor Language Server version 1.0.0-alpha2-20181112.3

Please also provide the following to help debug the issue:

1. Razor (cshtml) file content
```
@model BanUserEditModel
@{
    string trueName = ViewData.Get<string>("UserTureName", "");
}
@Html.AntiForgeryToken()
<div class="panel">
    <div class="panel-body">
        @using (Html.BeginAjaxForm("_BanUser", "ControlPanel", "", FormMethod.Post, new AjaxFormOptions { OnSuccessCallBack = "BanUserCallBack" }, new { @class = "tn-form-validation " }))
        {
        @Html.HiddenFor(m => m.UserId)
            <div class="form-group">
                <div class="row">
                    <div class="col-xs-12" style="width:100px">
                        @Html.LabelFor(m => m.BanDeadline)
                    </div>
                </div>
                <div class="input-group tn-width-300">
                    @Html.DateTimePickerFor(m => m.BanDeadline)
                </div>
                @Html.ValidationMessageFor(m => m.BanDeadline)
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-xs-12" style="width:100px">
                        @Html.LabelFor(m => m.BanReason)
                    </div>
                </div>
                @Html.TextBoxFor(m => m.BanReason, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.BanReason)
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary tn-mr-10 tn-btn-wp">确定</button>
                <button type="button" class="btn btn-default tn-btn-wp" data-dismiss="modal" id="cancel">关闭</button>
            </div>
        }
    </div>
</div>
@Styles.Render("~/js/lib/datetimepicker/css/bootstrap-datetimepikcer")
<script>
    require(['jquery'], function () {
        $(function () {
            $("#registeDate").val("")
        })
       
        //取消
        $("#cancel").click(function () {
            layer.closeAll();
        });

    })
</script>
```

**Comment by eevahr** [comment]
+1 fails regardless of open file but the one it happened with this time only has a script tag in it.

**Comment by NTaylorMullen** [comment]
@SmGG @eevahr thanks for the report! Would you mind providing a minimal project for me to reproduce the issue with? I'm unable to reproduce the issue with just the view sadly.

**Comment by eevahr** [comment]
this error occurs for me both in vscode and vscode-insiders with a fresh razor project (`dotnet new razor`), c# is the only extension installed.

**Comment by NTaylorMullen** [comment]
> i could upload the project, but it is as fresh as they come, so i don't see the point in doing so. I am happy to do it if you want it regardless.

If it's just `dotnet new razor` than I agree, no need 😄. Would you mind sharing your OS/architecture and the output of `dotnet --info`?

**Comment by SmGG** [comment]
```
.NET Core SDK（反映任何 global.json）:
 Version:   2.1.401
 Commit:    91b1c13032

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.401\

Host (useful for support):
  Version: 2.1.3-servicing-26724-03
  Commit:  124038c13e

.NET Core SDKs installed:
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

```

**Comment by SmGG** [comment]
for me it is just a  normal  .net mvc project @NTaylorMullen

**Comment by eevahr** [comment]
Out of office at the moment so dotnet --info will follow on monday. OS/arch is `win10 x64`.

**Comment by eevahr** [comment]
dotnet --info 
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.100-preview2-009404
 Commit:    f4707d384d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.100-preview2-009404\

Host (useful for support):
  Version: 2.2.0-preview2-26905-02
  Commit:  ad4d306fe0

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.400-preview-009171 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500-preview-009335 [C:\Program Files\dotnet\sdk]
  2.1.500-preview-009404 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.2.100-preview2-009404 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0-preview2-35157 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0-preview2-35157 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0-preview2-26905-02 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by NTaylorMullen** [comment]
Super weird... @david-driscoll have you ever seen anything like this before with the standalone omnisharp server?

**Comment by eevahr** [comment]
enabling razor.devmode seems to fix this problem for me... could just be the update to vscode 1.30 or .netcore 2.2 though.

**Comment by NTaylorMullen** [comment]
@eevahr, ya turning razor.devmode  to `true` or associating `*.cshtml` with `razor` result in the Razor LanguageServer not launching.

**Comment by eevahr** [comment]
I see, well then the razor languageserver has never really worked for me in vscode, so i am pretty stoked to see what it has to offer me :) That is if this issue gets resolved :)

**Comment by eevahr** [comment]
How is this going? I still get the error on `Razor.VSCode version 1.0.0-alpha2-20181112.3`

verbose output of error:
```
Unhandled Exception: [Info  - 11:17:45 AM] Finding descriptor for textDocument/didOpen
System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at System.Uri.CreateHostStringHelper(String str, UInt16 idx, UInt16 end, Flags& flags, String& scopeId)
   at System.Uri.CreateHostString()
   at System.Uri.EnsureHostString(Boolean allowDnsOptimization)
   at System.Uri.GetComponentsHelper(UriComponents uriComponents, UriFormat uriFormat)
   at System.Uri.ToString()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at OmniSharp.Extensions.LanguageServer.Server.Matchers.TextDocumentMatcher.FindHandler(Object parameters, IEnumerable`1 descriptors)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.FindDescriptor(String method, JToken params)
   at OmniSharp.Extensions.JsonRpc.InputHandler.HandleRequest(String request)
   at OmniSharp.Extensions.JsonRpc.InputHandler.ProcessInputStream()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
[Info  - 11:17:45 AM] Connection to server got closed. Server will restart.
[Info  - 11:17:46 AM] Razor Language Server version 1.0.0-alpha2-20181112.3
[Info  - 11:17:46 AM] Finished: Routing Notification initialized in 145ms
[Info  - 11:17:46 AM] Finding descriptor for textDocument/didOpen

Unhandled Exception: System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at System.Uri.CreateHostStringHelper(String str, UInt16 idx, UInt16 end, Flags& flags, String& scopeId)
   at System.Uri.CreateHostString()
   at System.Uri.EnsureHostString(Boolean allowDnsOptimization)
   at System.Uri.GetComponentsHelper(UriComponents uriComponents, UriFormat uriFormat)
   at System.Uri.ToString()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at OmniSharp.Extensions.LanguageServer.Server.Matchers.TextDocumentMatcher.FindHandler(Object parameters, IEnumerable`1 descriptors)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.FindDescriptor(String method, JToken params)
   at OmniSharp.Extensions.JsonRpc.InputHandler.HandleRequest(String request)
   at OmniSharp.Extensions.JsonRpc.InputHandler.ProcessInputStream()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
[Info  - 11:17:46 AM] Connection to server got closed. Server will restart.
[Info  - 11:17:47 AM] Razor Language Server version 1.0.0-alpha2-20181112.3
[Info  - 11:17:47 AM] Finished: Routing Notification initialized in 142ms
[Info  - 11:17:47 AM] Finding descriptor for textDocument/didOpen

Unhandled Exception: System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at System.Uri.CreateHostStringHelper(String str, UInt16 idx, UInt16 end, Flags& flags, String& scopeId)
   at System.Uri.CreateHostString()
   at System.Uri.EnsureHostString(Boolean allowDnsOptimization)
   at System.Uri.GetComponentsHelper(UriComponents uriComponents, UriFormat uriFormat)
   at System.Uri.ToString()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at OmniSharp.Extensions.LanguageServer.Server.Matchers.TextDocumentMatcher.FindHandler(Object parameters, IEnumerable`1 descriptors)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.FindDescriptor(String method, JToken params)
   at OmniSharp.Extensions.JsonRpc.InputHandler.HandleRequest(String request)
   at OmniSharp.Extensions.JsonRpc.InputHandler.ProcessInputStream()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
[Info  - 11:17:47 AM] Connection to server got closed. Server will restart.
[Info  - 11:17:48 AM] Razor Language Server version 1.0.0-alpha2-20181112.3
[Info  - 11:17:48 AM] Finished: Routing Notification initialized in 160ms
[Info  - 11:17:48 AM] Finding descriptor for textDocument/didOpen

Unhandled Exception: System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at System.Uri.CreateHostStringHelper(String str, UInt16 idx, UInt16 end, Flags& flags, String& scopeId)
   at System.Uri.CreateHostString()
   at System.Uri.EnsureHostString(Boolean allowDnsOptimization)
   at System.Uri.GetComponentsHelper(UriComponents uriComponents, UriFormat uriFormat)
   at System.Uri.ToString()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at OmniSharp.Extensions.LanguageServer.Server.Matchers.TextDocumentMatcher.FindHandler(Object parameters, IEnumerable`1 descriptors)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.FindDescriptor(String method, JToken params)
   at OmniSharp.Extensions.JsonRpc.InputHandler.HandleRequest(String request)
   at OmniSharp.Extensions.JsonRpc.InputHandler.ProcessInputStream()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
[Info  - 11:17:48 AM] Connection to server got closed. Server will restart.
[Info  - 11:17:49 AM] Razor Language Server version 1.0.0-alpha2-20181112.3
[Info  - 11:17:49 AM] Finished: Routing Notification initialized in 141ms
[Info  - 11:17:49 AM] Finding descriptor for textDocument/didOpen

Unhandled Exception: System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at System.Uri.CreateHostStringHelper(String str, UInt16 idx, UInt16 end, Flags& flags, String& scopeId)
   at System.Uri.CreateHostString()
   at System.Uri.EnsureHostString(Boolean allowDnsOptimization)
   at System.Uri.GetComponentsHelper(UriComponents uriComponents, UriFormat uriFormat)
   at System.Uri.ToString()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at OmniSharp.Extensions.LanguageServer.Server.Matchers.TextDocumentMatcher.FindHandler(Object parameters, IEnumerable`1 descriptors)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.FindDescriptor(String method, JToken params)
   at OmniSharp.Extensions.JsonRpc.InputHandler.HandleRequest(String request)
   at OmniSharp.Extensions.JsonRpc.InputHandler.ProcessInputStream()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
[Error - 11:17:49 AM] Connection to server got closed. Server will not be restarted.
```

This happens almost immediately when i open a .cshtml file.

**Comment by NTaylorMullen** [comment]
@eevahr i'm glad you're still thinking about this, holidays have definitely slowed the progress. As for a fix to this particular issue, i'm still not certain what the root cause is. Your environment seems correct. Do you happen to have mono installed on windows? Also, if you don't mind sharing, what's the file path of the project that is causing the issue (asking because it looks like the exception is a Uri exception)?

**Comment by eevahr** [comment]
@NTaylorMullen i'm glad you're still thinking about this aswell. I do not have mono installed. As for the filepath, my username includes `ø` and if i create a new project in `C:\project` this error disappears. So my guess is that something does not understand 'ø' and probably a lot of other characters.

**Comment by NTaylorMullen** [comment]
@eevahr Ahh! That would definitely be the issue then. @david-driscoll it looks like the omnisharp server protocol shouldn't entirely be relying on .NET's Uri implementation what do you think?

**Comment by eevahr** [comment]
Hey @NTaylorMullen, any progress/update on this issue?

**Comment by NTaylorMullen** [comment]
@eevahr, sadly not, need a response from @david-driscoll before I can move forward

**Comment by danroth27** [comment]
Is the issue here possibly that we need to enable IRI support in System.Uri?:

https://docs.microsoft.com/en-us/dotnet/framework/network-programming/international-resource-identifier-support-in-system-uri

Daniel Roth

**Comment by david-driscoll** [comment]
Sorry for the delay, been missing emails.

At the library level we're using the default `Uri` and I would hate to have to change that to a `string` (but if it turns out we have to, we can do it).  I don't see any specific issues when running in linq pad, but if we create a unit test that validates that.

It could also be the minimatch library... potentially looking at the stacks.

**Comment by david-driscoll** [comment]
I also wonder if this is logging related?  It's really strange...

**Comment by david-driscoll** [comment]
Trying to find a failing test...
https://github.com/OmniSharp/csharp-language-server-protocol/pull/130

**Comment by david-driscoll** [comment]
@eevahr is it possible to get an example project that shows this error?

Perhaps make a new folder on your C drive with your username, and see if you replicate this razor behavior in a `dotnet new` project.  Then if you can provide that as a zip, I can try and really debug what is going on.  At the moment I can't replicate on just the library side, so it maybe that vscode is doing something else that I can't easily see.

Thanks!

**Comment by NTaylorMullen** [comment]
Found a few more issues that look to be similar: 
- https://github.com/aspnet/Razor.VSCode/issues/298
- https://github.com/aspnet/Razor.VSCode/issues/291

**Comment by eevahr** [comment]
@david-driscoll sure! [here you go](https://file.io/TEe4yw)
i created a `dotnet new webapp` and zipped it up. 
I get the error in question on this project in vscode v1.32.3.

**Comment by eevahr** [comment]
I no longer have problems running the Razor Language Server version 1.0.0-alpha3-20190425.1.

**Comment by NTaylorMullen** [comment]
Interesting it must have been a bug with the version of .NET Core I was using. In alpha3 we upgraded to netcoreapp2.2; I'm betting that's what fixed it.
