### ISSUE TITLE
Language Server crashed

### ISSUE THREAD

**Issue by wanghaiwei** [aspnet/Razor.VSCode#353]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce
when I open vscode it always shows

#### Description of the problem:
i am using C# extension in vscode but always got 'Connection to server got closed. Server will not be restarted.'

Expected behavior:
Language Server run with no error

Actual behavior:
Connection to server got closed. Server will not be restarted.

#### Additional information

Please also provide the following to help debug the issue:

3. Verbose Razor log output. 
--------------------------------------------------------------------------------
Razor.VSCode version 1.0.0-alpha2.1-20190322.5
--------------------------------------------------------------------------------
Razor's trace level is currently set to 'Verbose'
 - To log issues with the Razor experience in VSCode you can file issues at https://github.com/aspnet/Razor.VSCode
 - To change Razor's trace level set 'razor.trace' to 'Off', 'Messages' or 'Verbose' and then restart VSCode.
-----------------------------------------------------------------------------------------------------------------------------

[Client - 上午11:15:28] Starting Razor Language Server...
[Client - 上午11:15:28] Server started, waiting for client to be ready...
[Info  - 上午11:15:29] Connection to server got closed. Server will restart.
[Info  - 上午11:15:30] Connection to server got closed. Server will restart.
[Info  - 上午11:15:30] Connection to server got closed. Server will restart.
[Info  - 上午11:15:31] Connection to server got closed. Server will restart.
[Error - 上午11:15:32] Connection to server got closed. Server will not be restarted.

4. OmniSharp log output. 
Starting OmniSharp server at 2019/4/11 上午11:29:49
    Target: /home/wanghaiwei/data/vscode/nue-computer-system-basis

OmniSharp server started.
    Path: /home/wanghaiwei/.vscode/extensions/ms-vscode.csharp-1.18.0/.omnisharp/1.32.11/run
    PID: 13761

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on manjaro 0.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 15.0 - "/home/wanghaiwei/.vscode/extensions/ms-vscode.csharp-1.18.0/.omnisharp/1.32.11/omnisharp/msbuild/15.0/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/home/wanghaiwei/.vscode/extensions/ms-vscode.csharp-1.18.0/.omnisharp/1.32.11/omnisharp/msbuild/15.0/Bin/MSBuild.dll'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 15.0 - "/home/wanghaiwei/.vscode/extensions/ms-vscode.csharp-1.18.0/.omnisharp/1.32.11/omnisharp/msbuild/15.0/Bin"
            MSBuildExtensionsPath = /home/wanghaiwei/.vscode/extensions/ms-vscode.csharp-1.18.0/.omnisharp/1.32.11/omnisharp/msbuild
            BypassFrameworkInstallChecks = true
            CscToolPath = /home/wanghaiwei/.vscode/extensions/ms-vscode.csharp-1.18.0/.omnisharp/1.32.11/omnisharp/msbuild/15.0/Bin/Roslyn
            CscToolExe = csc.exe
            MSBuildToolsPath = /home/wanghaiwei/.vscode/extensions/ms-vscode.csharp-1.18.0/.omnisharp/1.32.11/omnisharp/msbuild/15.0/Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/wanghaiwei/data/vscode/nue-computer-system-basis'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/home/wanghaiwei/data/vscode/nue-computer-system-basis'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/wanghaiwei/data/vscode/nue-computer-system-basis/nue-computer-system-basis.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/wanghaiwei/data/vscode/nue-computer-system-basis'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/wanghaiwei/data/vscode/nue-computer-system-basis/nue-computer-system-basis.csproj
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/wanghaiwei/data/vscode/nue-computer-system-basis' on host 13655.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/wanghaiwei/data/vscode/nue-computer-system-basis/nue-computer-system-basis.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/wanghaiwei/data/vscode/nue-computer-system-basis/nue-computer-system-basis.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: nue-computer-system-basis

**Comment by wanghaiwei** [comment]
i dont known what leat it crashed.The verbose mode shows nothing

**Comment by NTaylorMullen** [comment]
Interesting, @wanghaiwei does there happen to be any special characters in your path? Also, would it be possible to provide the output of `dotnet --info` and the OS/bitness you're encountering this on?

**Comment by wanghaiwei** [comment]
i confirm this is no any special characters
i saw someone meet this problem. i have removed this special characters and create a new projrct.
it still crrashed.
## this is my full path:
/home/wanghaiwei/data/vscode/neu-computer-system-basis/
## dotnet --info :
.NET Core SDK (reflecting any global.json):
 Version:   2.2.105
 Commit:    7cecb35b92

Runtime Environment:
 OS Name:     manjaro
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /opt/dotnet/sdk/2.2.105/

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.2.105 [/opt/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.2.3 [/opt/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by NTaylorMullen** [comment]
Thanks for the info @wanghaiwei i'll take a look and see if we've fixed this in our upcoming release 😄

**Comment by NTaylorMullen** [comment]
Thanks for the info @wanghaiwei i'll take a look and see if we've fixed this in our upcoming release 😄

**Comment by NTaylorMullen** [comment]
Thanks for the info @wanghaiwei i'll take a look and see if we've fixed this in our upcoming release 😄

**Comment by NTaylorMullen** [comment]
Just verified this is fixed in the next release 😄 

![image](https://i.imgur.com/sIntO0p.gif)

**Comment by wanghaiwei** [comment]
today i find this
> [2019-04-15 11:28:31.030] [renderer1] [error] Illegal argument: line must be non-negative: Error: Illegal argument: line must be non-negative
    at Object.t.illegalArgument (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:10:414)
    at new p (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:327:888)
    at new p (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:327:254)
    at CodeActionProvider.getInitializeFromCtorCommand (/home/wanghaiwei/.vscode/extensions/jchannon.csharpextensions-1.3.0/out/src/codeActionProvider.js:166:61)
    at addInitalizeFromCtor (/home/wanghaiwei/.vscode/extensions/jchannon.csharpextensions-1.3.0/out/src/codeActionProvider.js:15:28)
    at CodeActionProvider.provideCodeActions (/home/wanghaiwei/.vscode/extensions/jchannon.csharpextensions-1.3.0/out/src/codeActionProvider.js:19:9)
    at define.provideCodeActions.a.asPromise (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:587:847)
    at t.asPromise.Promise (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:49:430)
    at new Promise (<anonymous>:null:null)
    at Object.t.asPromise (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:49:402)
    at D.provideCodeActions (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:587:818)
    at define.$provideCodeActions._withAdapter.e (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:604:253)
    at B._withAdapter (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:599:159)
    at B.$provideCodeActions (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:604:231)
    at d._doInvokeHandler (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:622:11)
    at d._invokeHandler (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:621:716)
    at d._receiveRequest (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:620:341)
    at d._receiveOneMessage (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:619:141)
    at define.constructor._protocol.onMessage.e (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:617:400)
    at u.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:708)
    at e (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:40:460)
    at u.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:708)
    at a (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:172:467)
    at e (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:172:513)
    at u.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:708)
    at y._receiveMessage (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:181:276)
    at define.constructor._socketDisposables.push._socketReader.onMessage.e (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:178:415)
    at u.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:708)
    at f.acceptChunk (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:175:35)
    at define.constructor._register._socket.onData.e (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:174:410)
    at Socket.t (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:182:689)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20)

[2019-04-15 11:28:32.880] [renderer1] [error] Illegal argument: line must be non-negative: Error: Illegal argument: line must be non-negative
    at Object.t.illegalArgument (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:10:414)
    at new p (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:327:888)
    at new p (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:327:254)
    at CodeActionProvider.getInitializeFromCtorCommand (/home/wanghaiwei/.vscode/extensions/jchannon.csharpextensions-1.3.0/out/src/codeActionProvider.js:166:61)
    at addInitalizeFromCtor (/home/wanghaiwei/.vscode/extensions/jchannon.csharpextensions-1.3.0/out/src/codeActionProvider.js:15:28)
    at CodeActionProvider.provideCodeActions (/home/wanghaiwei/.vscode/extensions/jchannon.csharpextensions-1.3.0/out/src/codeActionProvider.js:19:9)
    at define.provideCodeActions.a.asPromise (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:587:847)
    at t.asPromise.Promise (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:49:430)
    at new Promise (<anonymous>:null:null)
    at Object.t.asPromise (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:49:402)
    at D.provideCodeActions (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:587:818)
    at define.$provideCodeActions._withAdapter.e (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:604:253)
    at B._withAdapter (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:599:159)
    at B.$provideCodeActions (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:604:231)
    at d._doInvokeHandler (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:622:11)
    at d._invokeHandler (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:621:716)
    at d._receiveRequest (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:620:341)
    at d._receiveOneMessage (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:619:141)
    at define.constructor._protocol.onMessage.e (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:617:400)
    at u.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:708)
    at e (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:40:460)
    at u.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:708)
    at a (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:172:467)
    at e (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:172:513)
    at u.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:708)
    at y._receiveMessage (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:181:276)
    at define.constructor._socketDisposables.push._socketReader.onMessage.e (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:178:415)
    at u.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:708)
    at f.acceptChunk (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:175:35)
    at define.constructor._register._socket.onData.e (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:174:410)
    at Socket.t (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:182:689)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20)

**Comment by NTaylorMullen** [comment]
@wanghaiwei is that a log from Razor's log? It looks unrelated.
