### ISSUE TITLE
Unhandled Exception: System.ArgumentNullException: Value cannot be null

### ISSUE THREAD

**Issue by dfdumaresq** [aspnet/Razor.VSCode#375]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce
- Restart VS Code or
- While in VS Code, switch Workspace.

#### Description of the problem:
Razor reports an Unhandled Exception.

#### Actual behavior:
See verbose Razor log output below:

--------------------------------------------------------------------------------
Razor.VSCode version 1.0.0-alpha3-20190606.2
--------------------------------------------------------------------------------
Razor's trace level is currently set to 'Verbose'
 - To change Razor's trace level set 'razor.trace' to 'Off', 'Messages' or 'Verbose' and then restart VSCode.
 - To report issues invoke the 'Report a Razor issue' command via the command palette.
-----------------------------------------------------------------------------------------------------------------------------

[Client - 10:53:48 AM] Razor language server path: /.vscode/extensions/ms-vscode.csharp-1.20.0/.razor/rzls
[Client - 10:53:49 AM] Starting Razor Language Server...
[Client - 10:53:49 AM] Server started, waiting for client to be ready...
[Client - 10:53:53 AM] Server started and ready!
[Info  - 10:53:54 AM] Razor Language Server version 1.0.0-alpha3-20190606.2
[Info  - 10:53:54 AM] Finished: Routing Notification initialized in 144ms
[Client - 10:53:55 AM] Notifying project '/sources/develop-branch/epbc-sts/src/EPBC.STS/EPBC.STS.csproj' - 'added'
[Client - 10:53:55 AM] Notifying project '/sources/develop-branch/epbc-middleware-client/EPBC.BusinessMiddleware.Client/EPBC.BusinessMiddleware.Client.csproj' - 'added'
[Client - 10:53:55 AM] Notifying project '/sources/develop-branch/epbc-ui/EPBC.PSAS.csproj' - 'added'
[Client - 10:53:55 AM] Notifying project '/sources/develop-branch/epbc-sts/src/EPBC.STS/EPBC.STS.csproj' - 'changed'
[Client - 10:53:55 AM] Notifying project '/sources/develop-branch/epbc-ui/EPBC.PSAS.csproj' - 'changed'
[Client - 10:53:56 AM] Notifying document '/sources/develop-branch/epbc-sts/src/EPBC.STS/Views/_ViewImports.cshtml' changed 'added'
[Client - 10:53:56 AM] Notifying document '/sources/develop-branch/epbc-sts/src/EPBC.STS/Views/_ViewStart.cshtml' changed 'added'
[Client - 10:53:56 AM] Notifying document '/sources/develop-branch/epbc-sts/src/EPBC.STS/Views/Home/Index.cshtml' changed 'added'
[Client - 10:53:56 AM] Notifying document '/sources/develop-branch/epbc-sts/src/EPBC.STS/Views/Shared/_Layout.cshtml' changed 'added'
[Client - 10:53:56 AM] Notifying document '/sources/develop-branch/epbc-sts/src/EPBC.STS/Views/Shared/Error.cshtml' changed 'added'
[Client - 10:53:56 AM] Notifying document '/sources/develop-branch/epbc-ui/Views/_ViewImports.cshtml' changed 'added'
[Client - 10:53:56 AM] Notifying document '/sources/develop-branch/epbc-ui/Views/Home/Index.cshtml' changed 'added'
[Client - 10:53:56 AM] Notifying document '/sources/develop-branch/epbc-ui/Views/Shared/_Layout.cshtml' changed 'added'
[Client - 10:53:56 AM] Notifying document '/sources/develop-branch/epbc-ui/Views/_ViewStart.cshtml' changed 'added'
[Info  - 10:53:56 AM] Finding descriptor for projects/addProject
[Info  - 10:53:56 AM] Starting: Routing Request (1) projects/addProject
[Info  - 10:53:56 AM] Converting params for Request (1) projects/addProject to Microsoft.AspNetCore.Razor.LanguageServer.ProjectSystem.RazorAddProjectParams
[Info  - 10:53:56 AM] Finding descriptor for projects/addProject
[Info  - 10:53:56 AM] Finding descriptor for projects/addProject
[Info  - 10:53:56 AM] Finding descriptor for projects/updateProject

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(Object value, String parameterName)
   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   at Newtonsoft.Json.Linq.Extensions.Value[U](IEnumerable`1 value)
   at Microsoft.AspNetCore.Razor.LanguageServer.Common.Serialization.TagHelperDescriptorJsonConverter.ReadRequiredAttribute(RequiredAttributeDescriptorBuilder builder, JObject attribute, JsonSerializer serializer) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/Serialization/TagHelperDescriptorJsonConverter.cs:line 317
   at Microsoft.AspNetCore.Razor.LanguageServer.Common.Serialization.TagHelperDescriptorJsonConverter.<>c__DisplayClass10_1.<ReadTagMatchingRule>b__0(RequiredAttributeDescriptorBuilder b) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/Serialization/TagHelperDescriptorJsonConverter.cs:line 300
   at Microsoft.AspNetCore.Razor.Language.DefaultTagMatchingRuleDescriptorBuilder.Attribute(Action`1 configure)
   at Microsoft.AspNetCore.Razor.LanguageServer.Common.Serialization.TagHelperDescriptorJsonConverter.ReadTagMatchingRule(TagMatchingRuleDescriptorBuilder builder, JObject rule, JsonSerializer serializer) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/Serialization/TagHelperDescriptorJsonConverter.cs:line 297
   at Microsoft.AspNetCore.Razor.LanguageServer.Common.Serialization.TagHelperDescriptorJsonConverter.<>c__DisplayClass2_1.<ReadJson>b__0(TagMatchingRuleDescriptorBuilder b) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/Serialization/TagHelperDescriptorJsonConverter.cs:line 50
   at Microsoft.AspNetCore.Razor.Language.DefaultTagHelperDescriptorBuilder.TagMatchingRule(Action`1 configure)
   at Microsoft.AspNetCore.Razor.LanguageServer.Common.Serialization.TagHelperDescriptorJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/Serialization/TagHelperDescriptorJsonConverter.cs:line 47
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.FindDescriptor(String method, JToken params)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.FindDescriptor(IMethodWithParams instance)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.GetDescriptor(Request request)
   at OmniSharp.Extensions.JsonRpc.InputHandler.HandleRequest(String request)
   at OmniSharp.Extensions.JsonRpc.InputHandler.ProcessInputStream()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[Error - 10:53:56 AM] Connection to server is erroring. Shutting down server.
[Error - 10:53:56 AM] Connection to server is erroring. Shutting down server.
[Error - 10:53:56 AM] Connection to server is erroring. Shutting down server.
[Client - 10:54:04 AM] Notifying project '/sources/develop-branch/epbc-ui/EPBC.PSAS.csproj' - 'changed'
[Client - 10:54:04 AM] Notifying project '/sources/develop-branch/epbc-ui/EPBC.PSAS.csproj' - 'changed'
[Client - 10:54:06 AM] Notifying project '/sources/develop-branch/epbc-ui/EPBC.PSAS.csproj' - 'changed'
[Client - 10:54:07 AM] Notifying project '/sources/develop-branch/epbc-ui/EPBC.PSAS.csproj' - 'changed'
[Client - 10:54:07 AM] Notifying project '/sources/develop-branch/epbc-ui/EPBC.PSAS.csproj' - 'changed'
[Client - 10:54:42 AM] -- Starting Issue Data Collection-- 
[Client - 10:54:56 AM] -- Stopping Issue Data Collection-- 

#### Additional information

Please also provide the following to help debug the issue:

1. Razor (cshtml) file content
None.

2. Generated C# code from the Razor CSharp Output in VS Code. 
None.

3. Verbose Razor log output.

See above

4. OmniSharp log output:

Starting OmniSharp server at 7/11/2019, 10:53:49 AM
    Target: /sources/develop-branch/epbc-ui/EPBC.PSAS.sln

OmniSharp server started.
    Path: /.vscode/extensions/ms-vscode.csharp-1.20.0/.omnisharp/1.32.20/run
    PID: 847

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 10.14.5 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 15.0 - "/.vscode/extensions/ms-vscode.csharp-1.20.0/.omnisharp/1.32.20/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/.vscode/extensions/ms-vscode.csharp-1.20.0/.omnisharp/1.32.20/omnisharp/.msbuild/Current/Bin/MSBuild.dll'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 15.0 - "/.vscode/extensions/ms-vscode.csharp-1.20.0/.omnisharp/1.32.20/omnisharp/.msbuild/Current/Bin"
            MSBuildExtensionsPath = /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/xbuild
            BypassFrameworkInstallChecks = true
            CscToolPath = /.vscode/extensions/ms-vscode.csharp-1.20.0/.omnisharp/1.32.20/omnisharp/.msbuild/Current/Bin/Roslyn
            CscToolExe = csc.exe
            MSBuildToolsPath = /.vscode/extensions/ms-vscode.csharp-1.20.0/.omnisharp/1.32.20/omnisharp/.msbuild/Current/Bin
            TargetFrameworkRootPath = /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/xbuild-frameworks
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/sources/develop-branch/epbc-ui'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/sources/develop-branch/epbc-ui/EPBC.PSAS.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/sources/develop-branch/epbc-ui/EPBC.PSAS.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/sources/develop-branch/epbc-middleware-client/EPBC.BusinessMiddleware.Client/EPBC.BusinessMiddleware.Client.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/sources/develop-branch/epbc-ui'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /sources/develop-branch/epbc-ui/EPBC.PSAS.csproj
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/sources/develop-branch/epbc-ui' on host 704.
[warn]: OmniSharp.MSBuild.ProjectLoader
        "/.vscode/extensions/ms-vscode.csharp-1.20.0/.omnisharp/1.32.20/omnisharp/.msbuild/Current/Bin/NuGet.targets" cannot be imported again. It was already imported at "/.vscode/extensions/ms-vscode.csharp-1.20.0/.omnisharp/1.32.20/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets (6060,3)". This is most likely a build authoring error. This subsequent import will be ignored. [/sources/develop-branch/epbc-middleware-client/EPBC.BusinessMiddleware.Client/EPBC.BusinessMiddleware.Client.csproj]
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/sources/develop-branch/epbc-ui/EPBC.PSAS.csproj'.
/sources/develop-branch/epbc-ui/EPBC.PSAS.csproj
/Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/xbuild/15.0/Microsoft.Common.targets/ImportAfter/Microsoft.NuGet.ImportAfter.targets(21,3): Error: "/.vscode/extensions/ms-vscode.csharp-1.20.0/.omnisharp/1.32.20/omnisharp/.msbuild/Current/Bin/NuGet.targets" cannot be imported again. It was already imported at "/.vscode/extensions/ms-vscode.csharp-1.20.0/.omnisharp/1.32.20/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets (6060,3)". This is most likely a build authoring error. This subsequent import will be ignored. [/sources/develop-branch/epbc-middleware-client/EPBC.BusinessMiddleware.Client/EPBC.BusinessMiddleware.Client.csproj]

[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/sources/develop-branch/epbc-ui/EPBC.PSAS.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /sources/develop-branch/epbc-middleware-client/EPBC.BusinessMiddleware.Client/EPBC.BusinessMiddleware.Client.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/sources/develop-branch/epbc-middleware-client/EPBC.BusinessMiddleware.Client/EPBC.BusinessMiddleware.Client.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/sources/develop-branch/epbc-middleware-client/EPBC.BusinessMiddleware.Client/EPBC.BusinessMiddleware.Client.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: EPBC.PSAS
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: EPBC.BusinessMiddleware.Client

**Comment by NTaylorMullen** [comment]
Thanks for the report @dfdumaresq. This is fixed in the next release 😄
