### ISSUE TITLE
Razor Server Crashed 5 times in the last X seconds 

### ISSUE THREAD

**Issue by tjbortz1s** [aspnet/Razor.VSCode#385]
I've been using VSCode with razor, and on occasion all intelisense fails to run and I eventually get a crash message.

The below are the crash logs for the program:

--------------------------------------------------------------------------------
Razor.VSCode version 1.0.0-alpha3-20190627.5
--------------------------------------------------------------------------------
Razor's trace level is currently set to 'Off'
 - To change Razor's trace level set 'razor.trace' to 'Off', 'Messages' or 'Verbose' and then restart VSCode.
 - To report issues invoke the 'Report a Razor issue' command via the command palette.
-----------------------------------------------------------------------------------------------------------------------------

Unhandled Exception: System.InvalidOperationException: 'StartWorkTimer' must be called on the foreground thread.
   at Microsoft.CodeAnalysis.Razor.ForegroundDispatcher.AssertForegroundThread(String caller)
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorDiagnosticsPublisher.StartWorkTimer() in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsPublisher.cs:line 93
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorDiagnosticsPublisher.WorkTimer_Tick(Object state) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsPublisher.cs:line 211
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
[Info  - 6:59:03 AM] Connection to server got closed. Server will restart.
[Error - 6:59:06 AM] Request textDocument/completion failed.
  Message: Internal Error - OmniSharp.Extensions.JsonRpc.Server.JsonRpcException: Exception of type 'OmniSharp.Extensions.JsonRpc.Server.JsonRpcException' was thrown.
   at OmniSharp.Extensions.JsonRpc.ResponseRouter.SendRequest[T,TResponse](String method, T params)
   at Microsoft.AspNetCore.Razor.LanguageServer.DefaultRemoteTextLoaderFactory.RemoteTextLoader.LoadTextAndVersionAsync(Workspace workspace, DocumentId documentId, CancellationToken cancellationToken) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRemoteTextLoaderFactory.cs:line 73
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextAsync()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultProjectSnapshotManager.<>c__DisplayClass19_0.<<DocumentOpened>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextVersionAsync()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.ComputedStateTracker.GetGeneratedOutputAndVersionCoreAsync(DefaultProjectSnapshot project, DocumentSnapshot document)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultDocumentSnapshot.GetGeneratedOutputAsync()
   at Microsoft.AspNetCore.Razor.LanguageServer.Completion.RazorCompletionEndpoint.Handle(CompletionParams request, CancellationToken cancellationToken) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionEndpoint.cs:line 100
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.RouteRequest(IHandlerDescriptor descriptor, Request request)
  Code: -32602 

Unhandled Exception: System.AggregateException: One or more errors occurred. (Exception of type 'OmniSharp.Extensions.JsonRpc.Server.JsonRpcException' was thrown.) ---> OmniSharp.Extensions.JsonRpc.Server.JsonRpcException: Exception of type 'OmniSharp.Extensions.JsonRpc.Server.JsonRpcException' was thrown.
   at OmniSharp.Extensions.JsonRpc.ResponseRouter.SendRequest[T,TResponse](String method, T params)
   at Microsoft.AspNetCore.Razor.LanguageServer.DefaultRemoteTextLoaderFactory.RemoteTextLoader.LoadTextAndVersionAsync(Workspace workspace, DocumentId documentId, CancellationToken cancellationToken) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRemoteTextLoaderFactory.cs:line 73
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextAsync()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultProjectSnapshotManager.<>c__DisplayClass19_0.<<DocumentOpened>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextVersionAsync()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.ComputedStateTracker.GetGeneratedOutputAndVersionCoreAsync(DefaultProjectSnapshot project, DocumentSnapshot document)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultDocumentSnapshot.GetGeneratedOutputAsync()
   at Microsoft.AspNetCore.Razor.LanguageServer.BackgroundDocumentGenerator.Timer_Tick(Object state) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/BackgroundDocumentGenerator.cs:line 212
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.TryGetTextVersion(VersionStamp& result)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextVersionAsync()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.ComputedStateTracker.GetImportsAsync(ProjectSnapshot project, DocumentSnapshot document)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.ComputedStateTracker.GetGeneratedOutputAndVersionCoreAsync(DefaultProjectSnapshot project, DocumentSnapshot document)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultDocumentSnapshot.GetGeneratedOutputAsync()
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorDiagnosticsPublisher.PublishDiagnosticsAsync(DocumentSnapshot document) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsPublisher.cs:line 156
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorDiagnosticsPublisher.WorkTimer_Tick(Object state) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsPublisher.cs:line 196
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
[Info  - 6:59:07 AM] Connection to server got closed. Server will restart.

Unhandled Exception: OmniSharp.Extensions.JsonRpc.Server.JsonRpcException: Exception of type 'OmniSharp.Extensions.JsonRpc.Server.JsonRpcException' was thrown.
   at OmniSharp.Extensions.JsonRpc.ResponseRouter.SendRequest[T,TResponse](String method, T params)
   at Microsoft.AspNetCore.Razor.LanguageServer.DefaultRemoteTextLoaderFactory.RemoteTextLoader.LoadTextAndVersionAsync(Workspace workspace, DocumentId documentId, CancellationToken cancellationToken) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRemoteTextLoaderFactory.cs:line 73
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextAsync()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultProjectSnapshotManager.<>c__DisplayClass19_0.<<DocumentOpened>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextVersionAsync()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.ComputedStateTracker.GetGeneratedOutputAndVersionCoreAsync(DefaultProjectSnapshot project, DocumentSnapshot document)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultDocumentSnapshot.GetGeneratedOutputAsync()
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorDiagnosticsPublisher.PublishDiagnosticsAsync(DocumentSnapshot document) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsPublisher.cs:line 156
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorDiagnosticsPublisher.WorkTimer_Tick(Object state) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsPublisher.cs:line 196
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
[Info  - 6:59:12 AM] Connection to server got closed. Server will restart.

Unhandled Exception: OmniSharp.Extensions.JsonRpc.Server.JsonRpcException: Exception of type 'OmniSharp.Extensions.JsonRpc.Server.JsonRpcException' was thrown.
   at OmniSharp.Extensions.JsonRpc.ResponseRouter.SendRequest[T,TResponse](String method, T params)
   at Microsoft.AspNetCore.Razor.LanguageServer.DefaultRemoteTextLoaderFactory.RemoteTextLoader.LoadTextAndVersionAsync(Workspace workspace, DocumentId documentId, CancellationToken cancellationToken) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRemoteTextLoaderFactory.cs:line 73
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextAsync()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultProjectSnapshotManager.<>c__DisplayClass19_0.<<DocumentOpened>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextVersionAsync()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.ComputedStateTracker.GetGeneratedOutputAndVersionCoreAsync(DefaultProjectSnapshot project, DocumentSnapshot document)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultDocumentSnapshot.GetGeneratedOutputAsync()
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorDiagnosticsPublisher.PublishDiagnosticsAsync(DocumentSnapshot document) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsPublisher.cs:line 156
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorDiagnosticsPublisher.WorkTimer_Tick(Object state) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsPublisher.cs:line 196
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
[Info  - 6:59:16 AM] Connection to server got closed. Server will restart.

Unhandled Exception: OmniSharp.Extensions.JsonRpc.Server.JsonRpcException: Exception of type 'OmniSharp.Extensions.JsonRpc.Server.JsonRpcException' was thrown.
   at OmniSharp.Extensions.JsonRpc.ResponseRouter.SendRequest[T,TResponse](String method, T params)
   at Microsoft.AspNetCore.Razor.LanguageServer.DefaultRemoteTextLoaderFactory.RemoteTextLoader.LoadTextAndVersionAsync(Workspace workspace, DocumentId documentId, CancellationToken cancellationToken) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRemoteTextLoaderFactory.cs:line 73
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextAsync()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultProjectSnapshotManager.<>c__DisplayClass19_0.<<DocumentOpened>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextVersionAsync()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.ComputedStateTracker.GetGeneratedOutputAndVersionCoreAsync(DefaultProjectSnapshot project, DocumentSnapshot document)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultDocumentSnapshot.GetGeneratedOutputAsync()
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorDiagnosticsPublisher.PublishDiagnosticsAsync(DocumentSnapshot document) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsPublisher.cs:line 156
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorDiagnosticsPublisher.WorkTimer_Tick(Object state) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsPublisher.cs:line 196
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
[Error - 6:59:20 AM] Connection to server got closed. Server will not be restarted.

If necessary/there is a private means to do so, I can send the file the program is crashing on to anyone who is part of the project.

**Comment by NTaylorMullen** [comment]
@tjbortz1s thanks for the crash report! This looks to be identical to https://github.com/aspnet/Razor.VSCode/issues/372

Going to close this for now so we can track the work over there.

**Comment by tjbortz1s** [comment]
Sounds great, thank you for your work on this project, it makes life a lot easier for me and I'm sure for a ton of other people as well.
